name: Update README with Stats
on:
  schedule:
    - cron: '0 */6 * * *' # runs every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          sed -i "s|username=Pranav-MSK|username=Pranav-MSK&token=${{ secrets.STATS_TOKEN }}|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update README with token"
          git push
